### ISSUE TITLE
Link to download data

### ISSUE THREAD

**Issue by nmtruong93** [coveooss/SIGIR-ecom-data-challenge#5]
Could you please give me the link to download data for this challenge? I can not see it.
Thank you.

**Comment by jeanfrancisroy** [comment]
Hello @nmtruong93, you will find the link to the download page in the Readme file, just below the "License" section:
https://github.com/coveooss/SIGIR-ecom-data-challenge#license

**Comment by nmtruong93** [comment]
Yes, saw it. Thank you @jeanfrancisroy
