### ISSUE TITLE
possible to get the dataset for training purposes?

### ISSUE THREAD

**Issue by hkorhola** [coveooss/SIGIR-ecom-data-challenge#7]
Hello

the form on the download page doesn't work, some error message and red banner at submit. Is it possible to get the dataset for playing with different data stacks @jacopotagliabue ?

**Comment by jacopotagliabue** [comment]
Hey, have you tried country=US?

**Comment by Sigmaaaa** [comment]
Getting the same problem here. A red banner with no text appears! I know and appreciate how much time went into this data set, and I am bummed it's not downloading. I would really appreciate a follow-up. Thanks!

**Comment by jacopotagliabue** [comment]
Thanks for the feedback @Sigmaaaa  and @hkorhola: as I'm not with the company [anymore](https://www.linkedin.com/in/jacopotagliabue/), you should ask Coveo directly. Please note that other datasets have also been released by my team for similar use cases (the most popular are [here](https://jacopotagliabue.it/)).

**Comment by CoveoBavoine** [comment]
Thanks for flagging this, I've fixed the ai labs forms

**Comment by Sigmaaaa** [comment]
> Thanks for flagging this, I've fixed the ai labs forms

Perfect! It's fixed now. Appreciate the quick response.

 Is there a reason why the form now says 200mb data instead of 1.8gb? Wondering if you guys removed part of the data or was it always ~200mb?

Thanks again!

**Comment by hkorhola** [comment]
Thanks now I got it via the form 👍 I think the size was ~2GB if I looked correctly.Sigmaaaa ***@***.***> kirjoitti 10.5.2024 kello 21.48:﻿

Thanks for flagging this, I've fixed the ai labs forms

Perfect! It's fixed now. Appreciate the quick response.
Is there a reason why the form now says 200mb data instead of 1.8gb? Wondering if you guys removed part of the data or was it always ~200mb?
Thanks again!

**Comment by hkorhola** [comment]
Thanks Jacopo will check your site in detail 🙌Jacopo Tagliabue ***@***.***> kirjoitti 10.5.2024 kello 3.49:﻿
Thanks for the feedback @Sigmaaaa  and @hkorhola: as I'm not with the company anymore, you should ask Coveo directly. Please note that other datasets have also been released by my team for similar use cases (the most popular are here).

**Comment by CoveoBavoine** [comment]
@Sigmaaaa I updated the titles as well to reflect the actual file sizes, the 1.8GB on the two others were a mistake. The file sizes are the same since they've been uploaded, from what I can see in the bucket.

Apologies if it caused any confusion 🙇
